version: '3.1'

services:

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nicasource
      POSTGRES_PASSWORD: nicasource
      POSTGRES_DB: videos_creator
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
