version: '3.1'

services:

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nicasource
      POSTGRES_PASSWORD: nicasource
      POSTGRES_DB: videos_creator
